### ISSUE TITLE
Header spacing

### ISSUE THREAD

**Issue by PeytonSorah** [VCUarts/Dance-2015#31]
make sure all headers, buttons, etc  have consistent and even spacing-right now things are looking kinda disjointed

**Comment by dstrogiy** [comment]
I'm going to concentrate on the spacing for headings, buttons and lists inside the content

**Comment by streeetlamp** [comment]
@PeytonSorah @dstrogiy is this good? plz close if so

**Comment by PeytonSorah** [comment]
@streeetlamp B-E-A-U-tiful
