### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/Dance-2015#53]
Tablet landscape and up is pretty much good, but need to figure out how to collapse the columns,etc for the tablet portrait and smaller.

Also need to figure out the mobile menu version for smaller phones - at the moment the logo and close button overlap with the text.

**Comment by PeytonSorah** [comment]
-[  ] Should we have search on mobile?

**Comment by dstrogiy** [comment]
I vote yes and uhh in nav probably?

**Comment by PeytonSorah** [comment]
Sounds good to me

**Comment by streeetlamp** [comment]
could use sculpture as an example, honestly not the biggest fan of the sculpture input area though

**Comment by dstrogiy** [comment]
![img_0704](https://cloud.githubusercontent.com/assets/6132788/10943131/2425d810-82e1-11e5-9847-18afd0fec7d4.PNG)

- [ ] looks like pagination is messing up the news archive on mobile
