### ISSUE TITLE
Mobile Menu

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/Dance-2015#54]
I think the SASS for mobile menu is being duplicated right now for some reason.

To do:
- [x] Clean up SASS
- [x] Add search
- [x] Hide logo on small phone screens when nav is open
- [x] Move close button on small phone screens (?) - maybe above the nav items?
- [x] add subnavs to mobile menu

**Comment by dstrogiy** [comment]
- [ ] At the moment, if you attempt to scroll through the menu on the phone, it closes.
- [ ] Less padding in search results on the phone
- [ ] Remove hover effects on mobile - they get stuck

**Comment by PeytonSorah** [comment]
- [ ] try out left aligned mobile comp
