### ISSUE TITLE
Page background

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/Dance-2015#7]
- [x] Need a default background - maybe texture or something
- [x] Child pages should inherit the page background from their parents
- [x] Same with single news posts - should inherit from news archive

**Comment by dstrogiy** [comment]
Also we gotta figure out how to do video background support, since it looks like they're going to send over videos for that

**Comment by streeetlamp** [comment]
the way these work will probably be tweaked but all pages should display SOME background now
