### ISSUE TITLE
Final Dance Edits

### ISSUE THREAD

**Issue by PeytonSorah** [VCUarts/Dance-2015#71]
- [x] back to top links-should these be on every page?
- [x] ability to caption background image (possibly also the lightbox capability that we had discussed?)
- [x] Home Page: We’re not into the big yellow letters just sitting in the middle of the page. Could they be
dynamic ­ i.e., could they each fade in and culminate in “VCU DANCE” (all caps)? Would that
be too much movement, over the video?
or, Gaynell likes the idea of the words fading in, in a cluster, with VCU DANCE in the middle.
- [x] Home Page: I think we had talked about a twitter feed in a sidebar or bottom bar on the home page, or
else the most current “News” entry/ies showing? It seems important to have the home page
reflect most current info, even in a small segment...
(In addition to the “Social Feed” page, which we love.)
Alumni page:​http://arts.vcu.edu/d2015/people/alumni/
- [x] The structure of this page should not mimic the Faculty & Staff page, with lists of people, but
rather list a collection of Highlights, more in the style of News.
Does this make sense?

- [x] People menu structure
- [x] add background images

**Comment by PeytonSorah** [comment]
BG image details overlay, you guys like? @dstrogiy @streeetlamp 

![screen shot 2015-11-11 at 11 51 34 am](https://cloud.githubusercontent.com/assets/7943826/11096983/ce9135e0-886a-11e5-92f4-1609b1a1ee8b.png)

![screen shot 2015-11-11 at 11 44 42 am](https://cloud.githubusercontent.com/assets/7943826/11096986/d4320164-886a-11e5-808a-8ed458b4eb96.png)

**Comment by dstrogiy** [comment]
Maybe it doesn't need to take that much space? What about a horisontal 1:2 ratio layout with an X in the top right to match search popup

**Comment by streeetlamp** [comment]
Social Feed is in progress, just some pain points Im working on btw
